services:
  train-app:
    image: lauraszilagyi/train_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongoadmin:secret@mongodb-train-app:27017/trains?authSource=admin
    container_name: train-app
    restart: unless-stopped
    depends_on:
      - mongodb-train-app
  mongodb-train-app:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - /tmp/mongodata:/data/db
    container_name: mongodb-train-app